- name: Install graphviz
  apt:
    name:
      - graphviz
      - graphviz-dev
    update_cache: true
  become: true

- name: Find bokeh directories
  find:
    paths: "{{ ansible_env.HOME }}/.local/lib"
    patterns: "*bokeh*"
    file_type: directory
    recurse: true
  register: bokeh_dirs

- name: Remove found bokeh directories
  file:
    path: "{{ item.path }}"
    state: absent
  loop: "{{ bokeh_dirs.files }}"
  become: false

- name: Install caret dependent packages
  pip:
    requirements: "{{ requirements_path }}"
    executable: pip3
    extra_args: --ignore-installed
  become: false
  args:
    chdir: "{{ WORKSPACE_ROOT }}"
  when: pip_install | default('y') == 'y'
